name: couchdb
description: CouchDB client written in Dart
version: 0.5.6
homepage: https://github.com/YevhenKap/couchdb_dart
author: Kapelianovych Yevhen <kapelianovych.y.v@gmail.com>
license: MIT

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  http: ^0.12.0
  crypto: ^2.1.3

dev_dependencies:
  test: ^1.9.1
  pedantic: ^1.8.0