name: couchdb
description: Library for interacting with CouchDB from both a server and browser environment
version: 0.5.4
homepage: https://github.com/YevhenKap/couchdb_dart
author: Kapelianovych Yevhen <kapelianovych.y.v@gmail.com>
license: MIT

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  http: ^0.12.0
  crypto: ^2.0.6

dev_dependencies:
  test: ^1.5.3